proxy-port: 8031 

#sync: true

connector: bala-mongo.core

servers:

 - name: doclayer
   host: localhost
   port: 8041

# - name: mongo v2.6
#   host: localhost
#   port: 27017 
   isolate-requests: true 
   primary: true

server-timeout: 5000

bala-mongo:
  max-wire-version: 0
  output: /home/tom/
