proxy-port: 8031

connector: bala-mongo.core

servers:

 - name: mongo v2.6
   host: localhost
   port: 27017
   primary: true

 - name: doclayer
   host: localhost
   port: 8041

server-timeout: 5000

